/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace OptionsVault {
  export type PositionStruct = {
    tokenId: BigNumberish;
    feedId: BytesLike;
    symbol: string;
    optionType: BigNumberish;
    strikeWad: BigNumberish;
    expiry: BigNumberish;
    sizeWad: BigNumberish;
    premiumWad: BigNumberish;
    writer: AddressLike;
    buyer: AddressLike;
    collateralToken: AddressLike;
    collateralWad: BigNumberish;
    scheduleId: AddressLike;
    settled: boolean;
  };

  export type PositionStructOutput = [
    tokenId: bigint,
    feedId: string,
    symbol: string,
    optionType: bigint,
    strikeWad: bigint,
    expiry: bigint,
    sizeWad: bigint,
    premiumWad: bigint,
    writer: string,
    buyer: string,
    collateralToken: string,
    collateralWad: bigint,
    scheduleId: string,
    settled: boolean
  ] & {
    tokenId: bigint;
    feedId: string;
    symbol: string;
    optionType: bigint;
    strikeWad: bigint;
    expiry: bigint;
    sizeWad: bigint;
    premiumWad: bigint;
    writer: string;
    buyer: string;
    collateralToken: string;
    collateralWad: bigint;
    scheduleId: string;
    settled: boolean;
  };

  export type QuoteParamsStruct = {
    symbol: string;
    optionType: BigNumberish;
    strikeWad: BigNumberish;
    expiry: BigNumberish;
    sizeWad: BigNumberish;
    sigmaWad: BigNumberish;
  };

  export type QuoteParamsStructOutput = [
    symbol: string,
    optionType: bigint,
    strikeWad: bigint,
    expiry: bigint,
    sizeWad: bigint,
    sigmaWad: bigint
  ] & {
    symbol: string;
    optionType: bigint;
    strikeWad: bigint;
    expiry: bigint;
    sizeWad: bigint;
    sigmaWad: bigint;
  };

  export type WriteParamsStruct = {
    symbol: string;
    optionType: BigNumberish;
    strikeWad: BigNumberish;
    expiry: BigNumberish;
    sizeWad: BigNumberish;
    sigmaWad: BigNumberish;
    collateralToken: AddressLike;
    pythUpdateData: BytesLike[];
  };

  export type WriteParamsStructOutput = [
    symbol: string,
    optionType: bigint,
    strikeWad: bigint,
    expiry: bigint,
    sizeWad: bigint,
    sigmaWad: bigint,
    collateralToken: string,
    pythUpdateData: string[]
  ] & {
    symbol: string;
    optionType: bigint;
    strikeWad: bigint;
    expiry: bigint;
    sizeWad: bigint;
    sigmaWad: bigint;
    collateralToken: string;
    pythUpdateData: string[];
  };
}

export declare namespace BlackScholes {
  export type BSMResultStruct = {
    premium: BigNumberish;
    delta: BigNumberish;
    gamma: BigNumberish;
    vega: BigNumberish;
    theta: BigNumberish;
    rho: BigNumberish;
  };

  export type BSMResultStructOutput = [
    premium: bigint,
    delta: bigint,
    gamma: bigint,
    vega: bigint,
    theta: bigint,
    rho: bigint
  ] & {
    premium: bigint;
    delta: bigint;
    gamma: bigint;
    vega: bigint;
    theta: bigint;
    rho: bigint;
  };
}

export interface OptionsVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_EXPIRY_DAYS"
      | "MIN_EXPIRY_SECS"
      | "PROTOCOL_FEE_WAD"
      | "PYTH_MAX_AGE"
      | "WAD"
      | "accruedFees"
      | "addCollateralToken"
      | "availableCollateral"
      | "collateralTokens"
      | "depositERC20"
      | "depositHBAR"
      | "exercise"
      | "expireOption"
      | "feedIds"
      | "getCollateralTokens"
      | "getPosition"
      | "getSupportedSymbols"
      | "intrinsicValue"
      | "isCollateralToken"
      | "optionToken"
      | "owner"
      | "pause"
      | "paused"
      | "positions"
      | "pyth"
      | "quotePremium"
      | "registerFeed"
      | "renounceOwnership"
      | "riskFreeRateWad"
      | "setRiskFreeRate"
      | "supportedSymbols"
      | "transferOwnership"
      | "unpause"
      | "withdrawCollateral"
      | "withdrawFees"
      | "writeOption"
      | "writerCollateral"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CollateralDeposited"
      | "CollateralWithdrawn"
      | "FeeCollected"
      | "FeedRegistered"
      | "OptionExercised"
      | "OptionExpired"
      | "OptionWritten"
      | "OwnershipTransferred"
      | "Paused"
      | "RiskFreeRateUpdated"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_EXPIRY_DAYS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_EXPIRY_SECS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PROTOCOL_FEE_WAD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PYTH_MAX_AGE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "WAD", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "accruedFees",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addCollateralToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "availableCollateral",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "collateralTokens",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositERC20",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositHBAR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "exercise",
    values: [BigNumberish, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "expireOption",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "feedIds", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getCollateralTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPosition",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSupportedSymbols",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "intrinsicValue",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isCollateralToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "optionToken",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "positions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "pyth", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "quotePremium",
    values: [OptionsVault.QuoteParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "registerFeed",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "riskFreeRateWad",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setRiskFreeRate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportedSymbols",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawCollateral",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFees",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "writeOption",
    values: [OptionsVault.WriteParamsStruct, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "writerCollateral",
    values: [AddressLike, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_EXPIRY_DAYS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_EXPIRY_SECS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PROTOCOL_FEE_WAD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PYTH_MAX_AGE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "WAD", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "accruedFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addCollateralToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "availableCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collateralTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositERC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositHBAR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "exercise", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "expireOption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "feedIds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCollateralTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSupportedSymbols",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "intrinsicValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isCollateralToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "optionToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "positions", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pyth", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "quotePremium",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerFeed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "riskFreeRateWad",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRiskFreeRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportedSymbols",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "writeOption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "writerCollateral",
    data: BytesLike
  ): Result;
}

export namespace CollateralDepositedEvent {
  export type InputTuple = [
    writer: AddressLike,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [writer: string, token: string, amount: bigint];
  export interface OutputObject {
    writer: string;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CollateralWithdrawnEvent {
  export type InputTuple = [
    writer: AddressLike,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [writer: string, token: string, amount: bigint];
  export interface OutputObject {
    writer: string;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeCollectedEvent {
  export type InputTuple = [token: AddressLike, amount: BigNumberish];
  export type OutputTuple = [token: string, amount: bigint];
  export interface OutputObject {
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeedRegisteredEvent {
  export type InputTuple = [symbol: string, feedId: BytesLike];
  export type OutputTuple = [symbol: string, feedId: string];
  export interface OutputObject {
    symbol: string;
    feedId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OptionExercisedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    exerciser: AddressLike,
    spotWad: BigNumberish,
    payoutWad: BigNumberish
  ];
  export type OutputTuple = [
    tokenId: bigint,
    exerciser: string,
    spotWad: bigint,
    payoutWad: bigint
  ];
  export interface OutputObject {
    tokenId: bigint;
    exerciser: string;
    spotWad: bigint;
    payoutWad: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OptionExpiredEvent {
  export type InputTuple = [tokenId: BigNumberish, automated: boolean];
  export type OutputTuple = [tokenId: bigint, automated: boolean];
  export interface OutputObject {
    tokenId: bigint;
    automated: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OptionWrittenEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    writer: AddressLike,
    buyer: AddressLike,
    symbol: string,
    optionType: BigNumberish,
    strikeWad: BigNumberish,
    sizeWad: BigNumberish,
    expiry: BigNumberish,
    premiumWad: BigNumberish,
    scheduleId: AddressLike
  ];
  export type OutputTuple = [
    tokenId: bigint,
    writer: string,
    buyer: string,
    symbol: string,
    optionType: bigint,
    strikeWad: bigint,
    sizeWad: bigint,
    expiry: bigint,
    premiumWad: bigint,
    scheduleId: string
  ];
  export interface OutputObject {
    tokenId: bigint;
    writer: string;
    buyer: string;
    symbol: string;
    optionType: bigint;
    strikeWad: bigint;
    sizeWad: bigint;
    expiry: bigint;
    premiumWad: bigint;
    scheduleId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RiskFreeRateUpdatedEvent {
  export type InputTuple = [newRateWad: BigNumberish];
  export type OutputTuple = [newRateWad: bigint];
  export interface OutputObject {
    newRateWad: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface OptionsVault extends BaseContract {
  connect(runner?: ContractRunner | null): OptionsVault;
  waitForDeployment(): Promise<this>;

  interface: OptionsVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_EXPIRY_DAYS: TypedContractMethod<[], [bigint], "view">;

  MIN_EXPIRY_SECS: TypedContractMethod<[], [bigint], "view">;

  PROTOCOL_FEE_WAD: TypedContractMethod<[], [bigint], "view">;

  PYTH_MAX_AGE: TypedContractMethod<[], [bigint], "view">;

  WAD: TypedContractMethod<[], [bigint], "view">;

  accruedFees: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  addCollateralToken: TypedContractMethod<
    [token: AddressLike],
    [void],
    "nonpayable"
  >;

  availableCollateral: TypedContractMethod<
    [writer: AddressLike, token: AddressLike],
    [bigint],
    "view"
  >;

  collateralTokens: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  depositERC20: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  depositHBAR: TypedContractMethod<[], [void], "payable">;

  exercise: TypedContractMethod<
    [tokenId: BigNumberish, pythUpdateData: BytesLike[]],
    [void],
    "payable"
  >;

  expireOption: TypedContractMethod<
    [tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  feedIds: TypedContractMethod<[arg0: string], [string], "view">;

  getCollateralTokens: TypedContractMethod<[], [string[]], "view">;

  getPosition: TypedContractMethod<
    [tokenId: BigNumberish],
    [OptionsVault.PositionStructOutput],
    "view"
  >;

  getSupportedSymbols: TypedContractMethod<[], [string[]], "view">;

  intrinsicValue: TypedContractMethod<
    [tokenId: BigNumberish, spotWad: BigNumberish],
    [bigint],
    "view"
  >;

  isCollateralToken: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  optionToken: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  positions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        string,
        bigint,
        string,
        boolean
      ] & {
        tokenId: bigint;
        feedId: string;
        symbol: string;
        optionType: bigint;
        strikeWad: bigint;
        expiry: bigint;
        sizeWad: bigint;
        premiumWad: bigint;
        writer: string;
        buyer: string;
        collateralToken: string;
        collateralWad: bigint;
        scheduleId: string;
        settled: boolean;
      }
    ],
    "view"
  >;

  pyth: TypedContractMethod<[], [string], "view">;

  quotePremium: TypedContractMethod<
    [q: OptionsVault.QuoteParamsStruct],
    [
      [bigint, BlackScholes.BSMResultStructOutput] & {
        premiumWad: bigint;
        greeks: BlackScholes.BSMResultStructOutput;
      }
    ],
    "view"
  >;

  registerFeed: TypedContractMethod<
    [symbol: string, feedId: BytesLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  riskFreeRateWad: TypedContractMethod<[], [bigint], "view">;

  setRiskFreeRate: TypedContractMethod<
    [rateWad: BigNumberish],
    [void],
    "nonpayable"
  >;

  supportedSymbols: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  withdrawCollateral: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawFees: TypedContractMethod<
    [token: AddressLike, to: AddressLike],
    [void],
    "nonpayable"
  >;

  writeOption: TypedContractMethod<
    [wp: OptionsVault.WriteParamsStruct, maxPremium: BigNumberish],
    [[bigint, bigint] & { tokenId: bigint; premiumWad: bigint }],
    "payable"
  >;

  writerCollateral: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_EXPIRY_DAYS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_EXPIRY_SECS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PROTOCOL_FEE_WAD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PYTH_MAX_AGE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "WAD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "accruedFees"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "addCollateralToken"
  ): TypedContractMethod<[token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "availableCollateral"
  ): TypedContractMethod<
    [writer: AddressLike, token: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "collateralTokens"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "depositERC20"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositHBAR"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "exercise"
  ): TypedContractMethod<
    [tokenId: BigNumberish, pythUpdateData: BytesLike[]],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "expireOption"
  ): TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "feedIds"
  ): TypedContractMethod<[arg0: string], [string], "view">;
  getFunction(
    nameOrSignature: "getCollateralTokens"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getPosition"
  ): TypedContractMethod<
    [tokenId: BigNumberish],
    [OptionsVault.PositionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSupportedSymbols"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "intrinsicValue"
  ): TypedContractMethod<
    [tokenId: BigNumberish, spotWad: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "isCollateralToken"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "optionToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "positions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        string,
        bigint,
        string,
        boolean
      ] & {
        tokenId: bigint;
        feedId: string;
        symbol: string;
        optionType: bigint;
        strikeWad: bigint;
        expiry: bigint;
        sizeWad: bigint;
        premiumWad: bigint;
        writer: string;
        buyer: string;
        collateralToken: string;
        collateralWad: bigint;
        scheduleId: string;
        settled: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "pyth"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "quotePremium"
  ): TypedContractMethod<
    [q: OptionsVault.QuoteParamsStruct],
    [
      [bigint, BlackScholes.BSMResultStructOutput] & {
        premiumWad: bigint;
        greeks: BlackScholes.BSMResultStructOutput;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerFeed"
  ): TypedContractMethod<
    [symbol: string, feedId: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "riskFreeRateWad"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setRiskFreeRate"
  ): TypedContractMethod<[rateWad: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportedSymbols"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawCollateral"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawFees"
  ): TypedContractMethod<
    [token: AddressLike, to: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "writeOption"
  ): TypedContractMethod<
    [wp: OptionsVault.WriteParamsStruct, maxPremium: BigNumberish],
    [[bigint, bigint] & { tokenId: bigint; premiumWad: bigint }],
    "payable"
  >;
  getFunction(
    nameOrSignature: "writerCollateral"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;

  getEvent(
    key: "CollateralDeposited"
  ): TypedContractEvent<
    CollateralDepositedEvent.InputTuple,
    CollateralDepositedEvent.OutputTuple,
    CollateralDepositedEvent.OutputObject
  >;
  getEvent(
    key: "CollateralWithdrawn"
  ): TypedContractEvent<
    CollateralWithdrawnEvent.InputTuple,
    CollateralWithdrawnEvent.OutputTuple,
    CollateralWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "FeeCollected"
  ): TypedContractEvent<
    FeeCollectedEvent.InputTuple,
    FeeCollectedEvent.OutputTuple,
    FeeCollectedEvent.OutputObject
  >;
  getEvent(
    key: "FeedRegistered"
  ): TypedContractEvent<
    FeedRegisteredEvent.InputTuple,
    FeedRegisteredEvent.OutputTuple,
    FeedRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "OptionExercised"
  ): TypedContractEvent<
    OptionExercisedEvent.InputTuple,
    OptionExercisedEvent.OutputTuple,
    OptionExercisedEvent.OutputObject
  >;
  getEvent(
    key: "OptionExpired"
  ): TypedContractEvent<
    OptionExpiredEvent.InputTuple,
    OptionExpiredEvent.OutputTuple,
    OptionExpiredEvent.OutputObject
  >;
  getEvent(
    key: "OptionWritten"
  ): TypedContractEvent<
    OptionWrittenEvent.InputTuple,
    OptionWrittenEvent.OutputTuple,
    OptionWrittenEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RiskFreeRateUpdated"
  ): TypedContractEvent<
    RiskFreeRateUpdatedEvent.InputTuple,
    RiskFreeRateUpdatedEvent.OutputTuple,
    RiskFreeRateUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "CollateralDeposited(address,address,uint256)": TypedContractEvent<
      CollateralDepositedEvent.InputTuple,
      CollateralDepositedEvent.OutputTuple,
      CollateralDepositedEvent.OutputObject
    >;
    CollateralDeposited: TypedContractEvent<
      CollateralDepositedEvent.InputTuple,
      CollateralDepositedEvent.OutputTuple,
      CollateralDepositedEvent.OutputObject
    >;

    "CollateralWithdrawn(address,address,uint256)": TypedContractEvent<
      CollateralWithdrawnEvent.InputTuple,
      CollateralWithdrawnEvent.OutputTuple,
      CollateralWithdrawnEvent.OutputObject
    >;
    CollateralWithdrawn: TypedContractEvent<
      CollateralWithdrawnEvent.InputTuple,
      CollateralWithdrawnEvent.OutputTuple,
      CollateralWithdrawnEvent.OutputObject
    >;

    "FeeCollected(address,uint256)": TypedContractEvent<
      FeeCollectedEvent.InputTuple,
      FeeCollectedEvent.OutputTuple,
      FeeCollectedEvent.OutputObject
    >;
    FeeCollected: TypedContractEvent<
      FeeCollectedEvent.InputTuple,
      FeeCollectedEvent.OutputTuple,
      FeeCollectedEvent.OutputObject
    >;

    "FeedRegistered(string,bytes32)": TypedContractEvent<
      FeedRegisteredEvent.InputTuple,
      FeedRegisteredEvent.OutputTuple,
      FeedRegisteredEvent.OutputObject
    >;
    FeedRegistered: TypedContractEvent<
      FeedRegisteredEvent.InputTuple,
      FeedRegisteredEvent.OutputTuple,
      FeedRegisteredEvent.OutputObject
    >;

    "OptionExercised(uint256,address,uint256,uint256)": TypedContractEvent<
      OptionExercisedEvent.InputTuple,
      OptionExercisedEvent.OutputTuple,
      OptionExercisedEvent.OutputObject
    >;
    OptionExercised: TypedContractEvent<
      OptionExercisedEvent.InputTuple,
      OptionExercisedEvent.OutputTuple,
      OptionExercisedEvent.OutputObject
    >;

    "OptionExpired(uint256,bool)": TypedContractEvent<
      OptionExpiredEvent.InputTuple,
      OptionExpiredEvent.OutputTuple,
      OptionExpiredEvent.OutputObject
    >;
    OptionExpired: TypedContractEvent<
      OptionExpiredEvent.InputTuple,
      OptionExpiredEvent.OutputTuple,
      OptionExpiredEvent.OutputObject
    >;

    "OptionWritten(uint256,address,address,string,uint8,uint256,uint256,uint256,uint256,address)": TypedContractEvent<
      OptionWrittenEvent.InputTuple,
      OptionWrittenEvent.OutputTuple,
      OptionWrittenEvent.OutputObject
    >;
    OptionWritten: TypedContractEvent<
      OptionWrittenEvent.InputTuple,
      OptionWrittenEvent.OutputTuple,
      OptionWrittenEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RiskFreeRateUpdated(uint256)": TypedContractEvent<
      RiskFreeRateUpdatedEvent.InputTuple,
      RiskFreeRateUpdatedEvent.OutputTuple,
      RiskFreeRateUpdatedEvent.OutputObject
    >;
    RiskFreeRateUpdated: TypedContractEvent<
      RiskFreeRateUpdatedEvent.InputTuple,
      RiskFreeRateUpdatedEvent.OutputTuple,
      RiskFreeRateUpdatedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
