/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../../common";

export interface IHRC755Interface extends Interface {
  getFunction(
    nameOrSignature: "authorizeSchedule" | "signSchedule"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "authorizeSchedule",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "signSchedule",
    values: [AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "authorizeSchedule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "signSchedule",
    data: BytesLike
  ): Result;
}

export interface IHRC755 extends BaseContract {
  connect(runner?: ContractRunner | null): IHRC755;
  waitForDeployment(): Promise<this>;

  interface: IHRC755Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorizeSchedule: TypedContractMethod<
    [schedule: AddressLike],
    [bigint],
    "nonpayable"
  >;

  signSchedule: TypedContractMethod<
    [schedule: AddressLike, signatureMap: BytesLike],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorizeSchedule"
  ): TypedContractMethod<[schedule: AddressLike], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "signSchedule"
  ): TypedContractMethod<
    [schedule: AddressLike, signatureMap: BytesLike],
    [bigint],
    "nonpayable"
  >;

  filters: {};
}
