/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../../common";

export declare namespace IHederaTokenService {
  export type KeyValueStruct = {
    inheritAccountKey: boolean;
    contractId: AddressLike;
    ed25519: BytesLike;
    ECDSA_secp256k1: BytesLike;
    delegatableContractId: AddressLike;
  };

  export type KeyValueStructOutput = [
    inheritAccountKey: boolean,
    contractId: string,
    ed25519: string,
    ECDSA_secp256k1: string,
    delegatableContractId: string
  ] & {
    inheritAccountKey: boolean;
    contractId: string;
    ed25519: string;
    ECDSA_secp256k1: string;
    delegatableContractId: string;
  };

  export type TokenKeyStruct = {
    keyType: BigNumberish;
    key: IHederaTokenService.KeyValueStruct;
  };

  export type TokenKeyStructOutput = [
    keyType: bigint,
    key: IHederaTokenService.KeyValueStructOutput
  ] & { keyType: bigint; key: IHederaTokenService.KeyValueStructOutput };

  export type ExpiryStruct = {
    second: BigNumberish;
    autoRenewAccount: AddressLike;
    autoRenewPeriod: BigNumberish;
  };

  export type ExpiryStructOutput = [
    second: bigint,
    autoRenewAccount: string,
    autoRenewPeriod: bigint
  ] & { second: bigint; autoRenewAccount: string; autoRenewPeriod: bigint };

  export type HederaTokenStruct = {
    name: string;
    symbol: string;
    treasury: AddressLike;
    memo: string;
    tokenSupplyType: boolean;
    maxSupply: BigNumberish;
    freezeDefault: boolean;
    tokenKeys: IHederaTokenService.TokenKeyStruct[];
    expiry: IHederaTokenService.ExpiryStruct;
  };

  export type HederaTokenStructOutput = [
    name: string,
    symbol: string,
    treasury: string,
    memo: string,
    tokenSupplyType: boolean,
    maxSupply: bigint,
    freezeDefault: boolean,
    tokenKeys: IHederaTokenService.TokenKeyStructOutput[],
    expiry: IHederaTokenService.ExpiryStructOutput
  ] & {
    name: string;
    symbol: string;
    treasury: string;
    memo: string;
    tokenSupplyType: boolean;
    maxSupply: bigint;
    freezeDefault: boolean;
    tokenKeys: IHederaTokenService.TokenKeyStructOutput[];
    expiry: IHederaTokenService.ExpiryStructOutput;
  };

  export type FixedFeeStruct = {
    amount: BigNumberish;
    tokenId: AddressLike;
    useHbarsForPayment: boolean;
    useCurrentTokenForPayment: boolean;
    feeCollector: AddressLike;
  };

  export type FixedFeeStructOutput = [
    amount: bigint,
    tokenId: string,
    useHbarsForPayment: boolean,
    useCurrentTokenForPayment: boolean,
    feeCollector: string
  ] & {
    amount: bigint;
    tokenId: string;
    useHbarsForPayment: boolean;
    useCurrentTokenForPayment: boolean;
    feeCollector: string;
  };

  export type FractionalFeeStruct = {
    numerator: BigNumberish;
    denominator: BigNumberish;
    minimumAmount: BigNumberish;
    maximumAmount: BigNumberish;
    netOfTransfers: boolean;
    feeCollector: AddressLike;
  };

  export type FractionalFeeStructOutput = [
    numerator: bigint,
    denominator: bigint,
    minimumAmount: bigint,
    maximumAmount: bigint,
    netOfTransfers: boolean,
    feeCollector: string
  ] & {
    numerator: bigint;
    denominator: bigint;
    minimumAmount: bigint;
    maximumAmount: bigint;
    netOfTransfers: boolean;
    feeCollector: string;
  };

  export type RoyaltyFeeStruct = {
    numerator: BigNumberish;
    denominator: BigNumberish;
    amount: BigNumberish;
    tokenId: AddressLike;
    useHbarsForPayment: boolean;
    feeCollector: AddressLike;
  };

  export type RoyaltyFeeStructOutput = [
    numerator: bigint,
    denominator: bigint,
    amount: bigint,
    tokenId: string,
    useHbarsForPayment: boolean,
    feeCollector: string
  ] & {
    numerator: bigint;
    denominator: bigint;
    amount: bigint;
    tokenId: string;
    useHbarsForPayment: boolean;
    feeCollector: string;
  };

  export type TokenInfoStruct = {
    token: IHederaTokenService.HederaTokenStruct;
    totalSupply: BigNumberish;
    deleted: boolean;
    defaultKycStatus: boolean;
    pauseStatus: boolean;
    fixedFees: IHederaTokenService.FixedFeeStruct[];
    fractionalFees: IHederaTokenService.FractionalFeeStruct[];
    royaltyFees: IHederaTokenService.RoyaltyFeeStruct[];
    ledgerId: string;
  };

  export type TokenInfoStructOutput = [
    token: IHederaTokenService.HederaTokenStructOutput,
    totalSupply: bigint,
    deleted: boolean,
    defaultKycStatus: boolean,
    pauseStatus: boolean,
    fixedFees: IHederaTokenService.FixedFeeStructOutput[],
    fractionalFees: IHederaTokenService.FractionalFeeStructOutput[],
    royaltyFees: IHederaTokenService.RoyaltyFeeStructOutput[],
    ledgerId: string
  ] & {
    token: IHederaTokenService.HederaTokenStructOutput;
    totalSupply: bigint;
    deleted: boolean;
    defaultKycStatus: boolean;
    pauseStatus: boolean;
    fixedFees: IHederaTokenService.FixedFeeStructOutput[];
    fractionalFees: IHederaTokenService.FractionalFeeStructOutput[];
    royaltyFees: IHederaTokenService.RoyaltyFeeStructOutput[];
    ledgerId: string;
  };

  export type FungibleTokenInfoStruct = {
    tokenInfo: IHederaTokenService.TokenInfoStruct;
    decimals: BigNumberish;
  };

  export type FungibleTokenInfoStructOutput = [
    tokenInfo: IHederaTokenService.TokenInfoStructOutput,
    decimals: bigint
  ] & {
    tokenInfo: IHederaTokenService.TokenInfoStructOutput;
    decimals: bigint;
  };

  export type NonFungibleTokenInfoStruct = {
    tokenInfo: IHederaTokenService.TokenInfoStruct;
    serialNumber: BigNumberish;
    ownerId: AddressLike;
    creationTime: BigNumberish;
    metadata: BytesLike;
    spenderId: AddressLike;
  };

  export type NonFungibleTokenInfoStructOutput = [
    tokenInfo: IHederaTokenService.TokenInfoStructOutput,
    serialNumber: bigint,
    ownerId: string,
    creationTime: bigint,
    metadata: string,
    spenderId: string
  ] & {
    tokenInfo: IHederaTokenService.TokenInfoStructOutput;
    serialNumber: bigint;
    ownerId: string;
    creationTime: bigint;
    metadata: string;
    spenderId: string;
  };
}

export interface IHRC756Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "getScheduledCreateFungibleTokenInfo"
      | "getScheduledCreateNonFungibleTokenInfo"
      | "scheduleNative"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getScheduledCreateFungibleTokenInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getScheduledCreateNonFungibleTokenInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "scheduleNative",
    values: [AddressLike, BytesLike, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getScheduledCreateFungibleTokenInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getScheduledCreateNonFungibleTokenInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scheduleNative",
    data: BytesLike
  ): Result;
}

export interface IHRC756 extends BaseContract {
  connect(runner?: ContractRunner | null): IHRC756;
  waitForDeployment(): Promise<this>;

  interface: IHRC756Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getScheduledCreateFungibleTokenInfo: TypedContractMethod<
    [scheduleAddress: AddressLike],
    [
      [bigint, IHederaTokenService.FungibleTokenInfoStructOutput] & {
        responseCode: bigint;
        fungibleTokenInfo: IHederaTokenService.FungibleTokenInfoStructOutput;
      }
    ],
    "nonpayable"
  >;

  getScheduledCreateNonFungibleTokenInfo: TypedContractMethod<
    [scheduleAddress: AddressLike],
    [
      [bigint, IHederaTokenService.NonFungibleTokenInfoStructOutput] & {
        responseCode: bigint;
        nonFungibleTokenInfo: IHederaTokenService.NonFungibleTokenInfoStructOutput;
      }
    ],
    "nonpayable"
  >;

  scheduleNative: TypedContractMethod<
    [
      systemContractAddress: AddressLike,
      callData: BytesLike,
      payer: AddressLike
    ],
    [[bigint, string] & { responseCode: bigint; scheduleAddress: string }],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getScheduledCreateFungibleTokenInfo"
  ): TypedContractMethod<
    [scheduleAddress: AddressLike],
    [
      [bigint, IHederaTokenService.FungibleTokenInfoStructOutput] & {
        responseCode: bigint;
        fungibleTokenInfo: IHederaTokenService.FungibleTokenInfoStructOutput;
      }
    ],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getScheduledCreateNonFungibleTokenInfo"
  ): TypedContractMethod<
    [scheduleAddress: AddressLike],
    [
      [bigint, IHederaTokenService.NonFungibleTokenInfoStructOutput] & {
        responseCode: bigint;
        nonFungibleTokenInfo: IHederaTokenService.NonFungibleTokenInfoStructOutput;
      }
    ],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "scheduleNative"
  ): TypedContractMethod<
    [
      systemContractAddress: AddressLike,
      callData: BytesLike,
      payer: AddressLike
    ],
    [[bigint, string] & { responseCode: bigint; scheduleAddress: string }],
    "nonpayable"
  >;

  filters: {};
}
