/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../../common";

export interface IHRC1215Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "deleteSchedule"
      | "executeCallOnPayerSignature"
      | "hasScheduleCapacity"
      | "scheduleCall"
      | "scheduleCallWithPayer"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "deleteSchedule",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeCallOnPayerSignature",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "hasScheduleCapacity",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "scheduleCall",
    values: [AddressLike, BigNumberish, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "scheduleCallWithPayer",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "deleteSchedule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeCallOnPayerSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasScheduleCapacity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scheduleCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scheduleCallWithPayer",
    data: BytesLike
  ): Result;
}

export interface IHRC1215 extends BaseContract {
  connect(runner?: ContractRunner | null): IHRC1215;
  waitForDeployment(): Promise<this>;

  interface: IHRC1215Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deleteSchedule: TypedContractMethod<
    [scheduleAddress: AddressLike],
    [bigint],
    "nonpayable"
  >;

  executeCallOnPayerSignature: TypedContractMethod<
    [
      to: AddressLike,
      payer: AddressLike,
      expirySecond: BigNumberish,
      gasLimit: BigNumberish,
      value: BigNumberish,
      callData: BytesLike
    ],
    [[bigint, string] & { responseCode: bigint; scheduleAddress: string }],
    "nonpayable"
  >;

  hasScheduleCapacity: TypedContractMethod<
    [expirySecond: BigNumberish, gasLimit: BigNumberish],
    [boolean],
    "view"
  >;

  scheduleCall: TypedContractMethod<
    [
      to: AddressLike,
      expirySecond: BigNumberish,
      gasLimit: BigNumberish,
      value: BigNumberish,
      callData: BytesLike
    ],
    [[bigint, string] & { responseCode: bigint; scheduleAddress: string }],
    "nonpayable"
  >;

  scheduleCallWithPayer: TypedContractMethod<
    [
      to: AddressLike,
      payer: AddressLike,
      expirySecond: BigNumberish,
      gasLimit: BigNumberish,
      value: BigNumberish,
      callData: BytesLike
    ],
    [[bigint, string] & { responseCode: bigint; scheduleAddress: string }],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deleteSchedule"
  ): TypedContractMethod<
    [scheduleAddress: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executeCallOnPayerSignature"
  ): TypedContractMethod<
    [
      to: AddressLike,
      payer: AddressLike,
      expirySecond: BigNumberish,
      gasLimit: BigNumberish,
      value: BigNumberish,
      callData: BytesLike
    ],
    [[bigint, string] & { responseCode: bigint; scheduleAddress: string }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasScheduleCapacity"
  ): TypedContractMethod<
    [expirySecond: BigNumberish, gasLimit: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "scheduleCall"
  ): TypedContractMethod<
    [
      to: AddressLike,
      expirySecond: BigNumberish,
      gasLimit: BigNumberish,
      value: BigNumberish,
      callData: BytesLike
    ],
    [[bigint, string] & { responseCode: bigint; scheduleAddress: string }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "scheduleCallWithPayer"
  ): TypedContractMethod<
    [
      to: AddressLike,
      payer: AddressLike,
      expirySecond: BigNumberish,
      gasLimit: BigNumberish,
      value: BigNumberish,
      callData: BytesLike
    ],
    [[bigint, string] & { responseCode: bigint; scheduleAddress: string }],
    "nonpayable"
  >;

  filters: {};
}
