/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IHRC1215 } from "./IHRC1215";
export type { IHRC755 } from "./IHRC755";
export type { IHRC756 } from "./IHRC756";
