/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IPyth {
  export type PriceStruct = {
    price: BigNumberish;
    conf: BigNumberish;
    expo: BigNumberish;
    publishTime: BigNumberish;
  };

  export type PriceStructOutput = [
    price: bigint,
    conf: bigint,
    expo: bigint,
    publishTime: bigint
  ] & { price: bigint; conf: bigint; expo: bigint; publishTime: bigint };

  export type PriceFeedStruct = {
    id: BytesLike;
    price: IPyth.PriceStruct;
    emaPrice: IPyth.PriceStruct;
  };

  export type PriceFeedStructOutput = [
    id: string,
    price: IPyth.PriceStructOutput,
    emaPrice: IPyth.PriceStructOutput
  ] & {
    id: string;
    price: IPyth.PriceStructOutput;
    emaPrice: IPyth.PriceStructOutput;
  };
}

export interface MockPythInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getEmaPriceNoOlderThan"
      | "getEmaPriceUnsafe"
      | "getPriceFeeds"
      | "getPriceNoOlderThan"
      | "getPriceUnsafe"
      | "getUpdateFee"
      | "priceFeedExists"
      | "setPrice"
      | "singleUpdateFeeInWei"
      | "updatePriceFeeds"
      | "updatePriceFeedsIfNecessary"
      | "validTimePeriod"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "PriceFeedUpdate"): EventFragment;

  encodeFunctionData(
    functionFragment: "getEmaPriceNoOlderThan",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEmaPriceUnsafe",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPriceFeeds",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getPriceNoOlderThan",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPriceUnsafe",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUpdateFee",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "priceFeedExists",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPrice",
    values: [BytesLike, BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "singleUpdateFeeInWei",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updatePriceFeeds",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePriceFeedsIfNecessary",
    values: [BytesLike[], BytesLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "validTimePeriod",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "getEmaPriceNoOlderThan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEmaPriceUnsafe",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPriceFeeds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPriceNoOlderThan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPriceUnsafe",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUpdateFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "priceFeedExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "singleUpdateFeeInWei",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePriceFeeds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePriceFeedsIfNecessary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validTimePeriod",
    data: BytesLike
  ): Result;
}

export namespace PriceFeedUpdateEvent {
  export type InputTuple = [
    id: BytesLike,
    publishTime: BigNumberish,
    price: BigNumberish,
    conf: BigNumberish
  ];
  export type OutputTuple = [
    id: string,
    publishTime: bigint,
    price: bigint,
    conf: bigint
  ];
  export interface OutputObject {
    id: string;
    publishTime: bigint;
    price: bigint;
    conf: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MockPyth extends BaseContract {
  connect(runner?: ContractRunner | null): MockPyth;
  waitForDeployment(): Promise<this>;

  interface: MockPythInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getEmaPriceNoOlderThan: TypedContractMethod<
    [id: BytesLike, age: BigNumberish],
    [IPyth.PriceStructOutput],
    "view"
  >;

  getEmaPriceUnsafe: TypedContractMethod<
    [id: BytesLike],
    [IPyth.PriceStructOutput],
    "view"
  >;

  getPriceFeeds: TypedContractMethod<
    [ids: BytesLike[]],
    [IPyth.PriceFeedStructOutput[]],
    "view"
  >;

  getPriceNoOlderThan: TypedContractMethod<
    [id: BytesLike, age: BigNumberish],
    [IPyth.PriceStructOutput],
    "view"
  >;

  getPriceUnsafe: TypedContractMethod<
    [id: BytesLike],
    [IPyth.PriceStructOutput],
    "view"
  >;

  getUpdateFee: TypedContractMethod<
    [updateData: BytesLike[]],
    [bigint],
    "view"
  >;

  priceFeedExists: TypedContractMethod<[id: BytesLike], [boolean], "view">;

  setPrice: TypedContractMethod<
    [
      feedId: BytesLike,
      price: BigNumberish,
      conf: BigNumberish,
      expo: BigNumberish,
      publishTime: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  singleUpdateFeeInWei: TypedContractMethod<[], [bigint], "view">;

  updatePriceFeeds: TypedContractMethod<
    [updateData: BytesLike[]],
    [void],
    "payable"
  >;

  updatePriceFeedsIfNecessary: TypedContractMethod<
    [arg0: BytesLike[], arg1: BytesLike[], arg2: BigNumberish[]],
    [void],
    "payable"
  >;

  validTimePeriod: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getEmaPriceNoOlderThan"
  ): TypedContractMethod<
    [id: BytesLike, age: BigNumberish],
    [IPyth.PriceStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEmaPriceUnsafe"
  ): TypedContractMethod<[id: BytesLike], [IPyth.PriceStructOutput], "view">;
  getFunction(
    nameOrSignature: "getPriceFeeds"
  ): TypedContractMethod<
    [ids: BytesLike[]],
    [IPyth.PriceFeedStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPriceNoOlderThan"
  ): TypedContractMethod<
    [id: BytesLike, age: BigNumberish],
    [IPyth.PriceStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPriceUnsafe"
  ): TypedContractMethod<[id: BytesLike], [IPyth.PriceStructOutput], "view">;
  getFunction(
    nameOrSignature: "getUpdateFee"
  ): TypedContractMethod<[updateData: BytesLike[]], [bigint], "view">;
  getFunction(
    nameOrSignature: "priceFeedExists"
  ): TypedContractMethod<[id: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "setPrice"
  ): TypedContractMethod<
    [
      feedId: BytesLike,
      price: BigNumberish,
      conf: BigNumberish,
      expo: BigNumberish,
      publishTime: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "singleUpdateFeeInWei"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "updatePriceFeeds"
  ): TypedContractMethod<[updateData: BytesLike[]], [void], "payable">;
  getFunction(
    nameOrSignature: "updatePriceFeedsIfNecessary"
  ): TypedContractMethod<
    [arg0: BytesLike[], arg1: BytesLike[], arg2: BigNumberish[]],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "validTimePeriod"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "PriceFeedUpdate"
  ): TypedContractEvent<
    PriceFeedUpdateEvent.InputTuple,
    PriceFeedUpdateEvent.OutputTuple,
    PriceFeedUpdateEvent.OutputObject
  >;

  filters: {
    "PriceFeedUpdate(bytes32,uint64,int64,uint64)": TypedContractEvent<
      PriceFeedUpdateEvent.InputTuple,
      PriceFeedUpdateEvent.OutputTuple,
      PriceFeedUpdateEvent.OutputObject
    >;
    PriceFeedUpdate: TypedContractEvent<
      PriceFeedUpdateEvent.InputTuple,
      PriceFeedUpdateEvent.OutputTuple,
      PriceFeedUpdateEvent.OutputObject
    >;
  };
}
