/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IHederaScheduleService {
  export type ScheduleInfoStruct = {
    scheduleId: AddressLike;
    scheduledTime: BigNumberish;
    executed: boolean;
    deleted: boolean;
    creator: AddressLike;
  };

  export type ScheduleInfoStructOutput = [
    scheduleId: string,
    scheduledTime: bigint,
    executed: boolean,
    deleted: boolean,
    creator: string
  ] & {
    scheduleId: string;
    scheduledTime: bigint;
    executed: boolean;
    deleted: boolean;
    creator: string;
  };
}

export interface IHederaScheduleServiceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cancelSchedule"
      | "getScheduleInfo"
      | "getSchedulingFee"
      | "scheduleCall"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ScheduleCancelled"
      | "ScheduleCreated"
      | "ScheduleExecuted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "cancelSchedule",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getScheduleInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSchedulingFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "scheduleCall",
    values: [AddressLike, BigNumberish, BigNumberish, BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "cancelSchedule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getScheduleInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSchedulingFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scheduleCall",
    data: BytesLike
  ): Result;
}

export namespace ScheduleCancelledEvent {
  export type InputTuple = [scheduleId: AddressLike, cancelledBy: AddressLike];
  export type OutputTuple = [scheduleId: string, cancelledBy: string];
  export interface OutputObject {
    scheduleId: string;
    cancelledBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ScheduleCreatedEvent {
  export type InputTuple = [
    creator: AddressLike,
    scheduleId: AddressLike,
    target: AddressLike,
    scheduledTime: BigNumberish
  ];
  export type OutputTuple = [
    creator: string,
    scheduleId: string,
    target: string,
    scheduledTime: bigint
  ];
  export interface OutputObject {
    creator: string;
    scheduleId: string;
    target: string;
    scheduledTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ScheduleExecutedEvent {
  export type InputTuple = [
    scheduleId: AddressLike,
    target: AddressLike,
    success: boolean
  ];
  export type OutputTuple = [
    scheduleId: string,
    target: string,
    success: boolean
  ];
  export interface OutputObject {
    scheduleId: string;
    target: string;
    success: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IHederaScheduleService extends BaseContract {
  connect(runner?: ContractRunner | null): IHederaScheduleService;
  waitForDeployment(): Promise<this>;

  interface: IHederaScheduleServiceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cancelSchedule: TypedContractMethod<
    [scheduleId: AddressLike],
    [void],
    "nonpayable"
  >;

  getScheduleInfo: TypedContractMethod<
    [scheduleId: AddressLike],
    [IHederaScheduleService.ScheduleInfoStructOutput],
    "view"
  >;

  getSchedulingFee: TypedContractMethod<[], [bigint], "view">;

  scheduleCall: TypedContractMethod<
    [
      targetContract: AddressLike,
      expirySecond: BigNumberish,
      gasLimit: BigNumberish,
      amount: BigNumberish,
      callData: BytesLike
    ],
    [[bigint, string] & { responseCode: bigint; scheduleAddress: string }],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cancelSchedule"
  ): TypedContractMethod<[scheduleId: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getScheduleInfo"
  ): TypedContractMethod<
    [scheduleId: AddressLike],
    [IHederaScheduleService.ScheduleInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSchedulingFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "scheduleCall"
  ): TypedContractMethod<
    [
      targetContract: AddressLike,
      expirySecond: BigNumberish,
      gasLimit: BigNumberish,
      amount: BigNumberish,
      callData: BytesLike
    ],
    [[bigint, string] & { responseCode: bigint; scheduleAddress: string }],
    "nonpayable"
  >;

  getEvent(
    key: "ScheduleCancelled"
  ): TypedContractEvent<
    ScheduleCancelledEvent.InputTuple,
    ScheduleCancelledEvent.OutputTuple,
    ScheduleCancelledEvent.OutputObject
  >;
  getEvent(
    key: "ScheduleCreated"
  ): TypedContractEvent<
    ScheduleCreatedEvent.InputTuple,
    ScheduleCreatedEvent.OutputTuple,
    ScheduleCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ScheduleExecuted"
  ): TypedContractEvent<
    ScheduleExecutedEvent.InputTuple,
    ScheduleExecutedEvent.OutputTuple,
    ScheduleExecutedEvent.OutputObject
  >;

  filters: {
    "ScheduleCancelled(address,address)": TypedContractEvent<
      ScheduleCancelledEvent.InputTuple,
      ScheduleCancelledEvent.OutputTuple,
      ScheduleCancelledEvent.OutputObject
    >;
    ScheduleCancelled: TypedContractEvent<
      ScheduleCancelledEvent.InputTuple,
      ScheduleCancelledEvent.OutputTuple,
      ScheduleCancelledEvent.OutputObject
    >;

    "ScheduleCreated(address,address,address,uint256)": TypedContractEvent<
      ScheduleCreatedEvent.InputTuple,
      ScheduleCreatedEvent.OutputTuple,
      ScheduleCreatedEvent.OutputObject
    >;
    ScheduleCreated: TypedContractEvent<
      ScheduleCreatedEvent.InputTuple,
      ScheduleCreatedEvent.OutputTuple,
      ScheduleCreatedEvent.OutputObject
    >;

    "ScheduleExecuted(address,address,bool)": TypedContractEvent<
      ScheduleExecutedEvent.InputTuple,
      ScheduleExecutedEvent.OutputTuple,
      ScheduleExecutedEvent.OutputObject
    >;
    ScheduleExecuted: TypedContractEvent<
      ScheduleExecutedEvent.InputTuple,
      ScheduleExecutedEvent.OutputTuple,
      ScheduleExecutedEvent.OutputObject
    >;
  };
}
