/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IHRC755,
  IHRC755Interface,
} from "../../../../../../@hashgraph/smart-contracts/contracts/system-contracts/hedera-schedule-service/IHRC755";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "schedule",
        type: "address",
      },
    ],
    name: "authorizeSchedule",
    outputs: [
      {
        internalType: "int64",
        name: "responseCode",
        type: "int64",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "schedule",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "signatureMap",
        type: "bytes",
      },
    ],
    name: "signSchedule",
    outputs: [
      {
        internalType: "int64",
        name: "responseCode",
        type: "int64",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IHRC755__factory {
  static readonly abi = _abi;
  static createInterface(): IHRC755Interface {
    return new Interface(_abi) as IHRC755Interface;
  }
  static connect(address: string, runner?: ContractRunner | null): IHRC755 {
    return new Contract(address, _abi, runner) as unknown as IHRC755;
  }
}
