/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IHRC1215__factory } from "./IHRC1215__factory";
export { IHRC755__factory } from "./IHRC755__factory";
export { IHRC756__factory } from "./IHRC756__factory";
