/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as hederaScheduleService from "./hedera-schedule-service";
export type { hederaScheduleService };
import type * as hederaTokenService from "./hedera-token-service";
export type { hederaTokenService };
